app/flask_app/dcs/controller.py
import datetime

import flask
from flask import Blueprint, render_template, request, Response, send_file, make_response
import json
from sqlalchemy import select, and_
import arrow
import os
from misc.t_dcs import MissionSearcher
import zipfile
import io
from pathlib import Path
from app import config

dcs = Blueprint(
    'dcs',
    __name__,
)


@dcs.route('/', methods=['GET'])
def landing():
    return render_template(
        'dcs/base.html',
    )


@dcs.route('/upload', methods=['POST'])
def upload():
    """
    TODO
        Throw client-side error if they select >2 files
        Change font size based on character count
        Include axis
            slew button
            slider
        Resize to be kneeboard sized?
        Include none-controller modifiers (e.g. keyboard)
    :return:
    """
    try:
        stick, throttle = config.CONTROL_MAPPER.render_controls(request.files['controls'].read())
        if 'controls2' in request.files:
            # user uploaded two files
            stick2, throttle2 = config.CONTROL_MAPPER.render_controls(request.files['controls2'].read())
            # we are not sure which file we parsed first. there are better ways to do this, but this is fastest :0
            if not stick:
                stick = stick2
            elif not throttle:
                throttle = throttle2

        return render_template(
            'dcs/hotas.html',
            joystick=stick,
            throttle=throttle,
        )
    except Exception as e:
        print(e)
        return str(e), 400


@dcs.route('/missions', methods=['GET', 'POST'])
def list_missions():
    if request.method == 'GET':
        modules = select([
            config.DCS_MODULE_TABLE.c.id,
            config.DCS_MODULE_TABLE.c.name,
        ]).order_by(
            config.DCS_MODULE_TABLE.c.name,
        ).execute().fetchall()

        return render_template(
            'dcs/mission.html',
            modules=modules,
        )
    else:
        # find matching missions
        pilot_mapping = {}

        desired_modules = request.json['modules']
        desired_count = [int(x) for x in request.json['counts']]
        desired_cap = sum(desired_count) + int(request.json['cap'])

        # build the where statement
        for x, module in enumerate(desired_modules):
            pilot_mapping[int(module)] = desired_count[x]
        print(pilot_mapping)

        # ok, now build a list of slots available in the mission
        results = select([
            config.DCS_MISSION_TABLE.c.id,
        ]).execute().fetchall()

        missions = [x.id for x in results]
        # how many missions have the _slots_ we desire
        match_count = 0

        matched_details = []
        # select details for matched missions
        for mission in missions:
            results = select([
                config.DCS_MISSION_TABLE.c.id,
                config.DCS_MISSION_TABLE.c.name.label('mission_name'),
                config.DCS_MISSION_TABLE.c.map,
                config.DCS_MISSION_TABLE.c.start_time,
                config.DCS_MISSION_TABLE.c.ed_id,
                config.DCS_MISSION_TABLE.c.ed_upload_date,
            ]).where(
                config.DCS_MISSION_TABLE.c.id == mission
            ).execute().fetchall()
            for result in results:
                details = {
                    'terrain': result.map,
                    'time': result.start_time,
                    'factions': {
                        'blue': {
                            'aircraft': {},
                        },
                        'red': {
                            'aircraft': {},
                        },
                    },
                    'total_slots': 0,
                    'id': result.id,
                    'name': result.mission_name,
                    'ed_id': result.ed_id,
                    'ed_date': result.ed_upload_date,
                }
                # get aircraft in the mission
                raw_planes = select([
                    config.DCS_MODULE_TABLE.c.id,
                    config.DCS_MODULE_TABLE.c.name,
                    config.DCS_M_M_TABLE.c.module_count,
                ]).select_from(
                    config.DCS_MODULE_TABLE.join(
                        config.DCS_M_M_TABLE,
                        config.DCS_MODULE_TABLE.c.id == config.DCS_M_M_TABLE.c.module_id,
                    )
                ).where(
                    config.DCS_M_M_TABLE.c.mission_id == mission
                ).execute().fetchall()

                met_criteria = None

                parsed_planes = {}
                for plane in raw_planes:
                    parsed_planes[plane.id] = {
                        'name': plane.name,
                        'count': plane.module_count,
                    }

                for module, desired_module_count in pilot_mapping.items():
                    # check if it's in the mission, if it has the count, AND if we haven't already failed to meet these criteria
                    if module in parsed_planes.keys() and parsed_planes[module]['count'] >= desired_module_count:
                        if met_criteria is None:
                            # avoid setting it to true if we've already set it to false
                            met_criteria = True
                    else:
                        met_criteria = False
                if met_criteria:
                    match_count += 1
                for plane in raw_planes:
                    details['factions']['blue']['aircraft'][plane.name] = plane.module_count
                    details['total_slots'] += plane.module_count
                if details['total_slots'] > desired_cap or not met_criteria:
                    continue
                matched_details.append(details)
        matched_details = sorted(matched_details, key=lambda k: k['total_slots'])
        mission_count = len(select([config.DCS_MISSION_TABLE.c.id]).execute().fetchall())
        print("found a total of {} missions".format(len(matched_details)))

        return Response(
            json.dumps({
                'status': render_template(
                    'dcs/mission_filter_results.html',
                    missions=matched_details,
                    mission_count=mission_count,
                    match_count=match_count,
                    match_count_filtered=len(matched_details),
                )
            }),
            mimetype='application/json'
        )


@dcs.route('/stats', methods=['GET'])
def mission_stats():

    missions = select([
        config.DCS_MISSION_TABLE.c.ed_upload_date,
    ]).order_by(
        config.DCS_MISSION_TABLE.c.ed_upload_date,
    ).execute().fetchall()

    last_upload = arrow.now().floor('month')
    missions_uploaded = {}
    cumulative_upload = {}

    sorted_data = {
        'dates': [],
        'total': [],
        'by_month': [],
    }

    # populate data
    total = 0
    for row in missions:
        total += 1
        current_upload = str(arrow.get(row[0]).floor('month').year)
        if current_upload not in missions_uploaded:
            missions_uploaded[current_upload] = 0
        missions_uploaded[current_upload] += 1
        cumulative_upload[current_upload] = total

    current_upload = arrow.get(missions[0][0]).floor('month')
    # backfill months while iterating over every month
    x = 0
    while current_upload < last_upload:
        # add the date to our known dates
        sorted_data['dates'].append(
            str(current_upload.year)
        )
        # check if the date is known and add the individual point if it is
        if str(current_upload.year) not in missions_uploaded:
            sorted_data['by_month'].append(
                0
            )
            # we also have cumulative data for this date
            sorted_data['total'].append(
                sorted_data['total'][x - 1]
            )
        else:
            sorted_data['by_month'].append(
                missions_uploaded[str(current_upload.year)]
            )
            # we don't have cumulative data for this date, pick it from the previous date
            sorted_data['total'].append(
                cumulative_upload[str(current_upload.year)]
            )
        x += 1
        current_upload = current_upload.shift(years=1)

    return render_template(
        'dcs/mission_stats.html',
        uploaded=missions_uploaded,
        cumulative=cumulative_upload,
        sorted_data=sorted_data,
    )


@dcs.route('/kneeboard', methods=['GET', 'POST'])
def kneeboard():
    if request.method == 'GET':
        return render_template(
            'dcs/kneeboard.html',
        )
    elif request.method == 'POST':
        pages = [
            Path('C:\\Users\\Tim\\Pictures\\st_logo_transparent_yt_style.0.png'),
        ]
        try:
            in_memory_zip = io.BytesIO()
            data = io.BytesIO(request.files['msn'].getvalue())
            in_len = data.getbuffer().nbytes

            with zipfile.ZipFile(in_memory_zip, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
                for file_name, contents in extract_zip(data).items():
                    zf.writestr(file_name, contents)
                for page in pages:
                    zf.write(page, 'KNEEBOARD\\F-14B\\IMAGES\\1.png')

            in_memory_zip.seek(0)
            out_len = in_memory_zip.getbuffer().nbytes
            extract_zip(in_memory_zip)
            in_memory_zip.seek(0)
            print(f"IN: {in_len} OUT: {out_len}")
            return send_file(in_memory_zip, attachment_filename=request.files['msn'].filename, as_attachment=True)
        except Exception as e:
            return Response(
                str(e),
                500
            )


def extract_zip(contents):
    input_zip = zipfile.ZipFile(contents, 'r')
    contents = {}
    for file in input_zip.namelist():
        contents[file] = input_zip.read(file)
    return contents

app/flask_app/templates/dcs/base.html
{% extends "base.html" %}

{% block body %}
    <script>
        function save_pic(controller) {
            var link = document.createElement("a");
            link.setAttribute("href", $('#' + controller + '_data').attr('src'));
            link.setAttribute("download", controller + '.png');
            link.click();
        }
        function upload(data) {
            console.log(data);
            $.ajax({
                url: "{{ url_for('dcs.upload') }}",
                type: 'POST',
                data: data,
                processData: false,  // tell jQuery not to process the data
                contentType: false,  // tell jQuery not to set contentType
                success: function(data) {
                    $("#stick").html(data.split('|')[0]);
                    $("#throttle").html(data.split('|')[1]);
                    $("#stick_save").on("click", function(){
                        save_pic('stick');
                    });
                    $("#throttle_save").on("click", function(){
                        save_pic('throttle');
                    });
                    return;
                },
                error: function(xhr, text, error) {
                    $("#error_content").text(xhr.responseText);
                    $('.ui.modal').modal('show');
                },
            });
        }

        function dropHandler(ev) {
            // Prevent default behavior (Prevent file from being opened)
            ev.preventDefault();

            if (ev.dataTransfer.items) {
                var file = ev.dataTransfer.files;
                var fd = new FormData();
                fd.append('controls', file[0]);
                // we only support two files. if they drag more, tough.
                if (file.length > 1)
                    fd.append('controls2', file[1]);
                upload(fd);
            }
        }

        function dragOverHandler(ev) {
            // Prevent default behavior (Prevent file from being opened)
            ev.preventDefault();
        }
    </script>
    <div class="ui grid">
        <div class="centered row">
            <div class="ui message">
                <i class="close icon"></i>
                <div class="header">
                    Control mapper
                </div>
                <p>This page parses control mappings and creates a visual representation of what's bound to what</p>
                <p><b>Note:</b> Currently only the Warthog and X52 are supported</p>
            </div>
        </div>
        <div class="row">
            <div class="seven wide column"></div>
            <ol class="ui list">
                <li>
                    Export controls
                    <ol>
                        <li>Launch DCS</li>
                        <li>Click "Options"</li>
                        <li>Click "Controls"</li>
                        <li>Select aircraft</li>
                        <li>Click "Make HTML"</li>
                    </ol>
                </li>
                <li>Upload controls (Warthog is two files; X52 is one)</li>
                <li>Download visual control representation</li>
            </ol>
        </div>

        <div class="centered row">
            <div class="ui center aligned basic segment">
                  <form method="post" id="myform">
                        <div class="field">
                            <div class="ui action input">
                                <label for="controls" class="ui icon button">
                                    <i class="attach icon"></i>
                                    Upload
                                    <input type="file" id="controls" name="controls" style="display: none">
                                </label>
                            </div>
                        </div>
                    </form>
                  <div class="ui horizontal divider">
                    Or
                  </div>
                    <div class="ui blue inverted segment" ondrop="dropHandler(event);" ondragover="dragOverHandler(event);">
                        Drag and drop
                        <i class="upload icon"></i>
                    </div>
            </div>
        </div>
        <div class="row">
            <div class="five wide column"></div>
            <div class="three wide column">
                <div id="stick"></div>
            </div>
            <div class="three wide column">
                <div id="throttle"></div>
            </div>
            <div class="five wide column"></div>
        </div>
    </div>

    <div id="error" class="ui modal">
        <div class="header">Error</div>
        <div id="error_content" class="content"></div>
    </div>

    <script>
        $(document).ready(function () {
            $("#controls").change(function(){
                var formData = new FormData($("#myform")[0]);
                console.log(formData);
                upload(formData);
            });
        });
    </script>
{% endblock %}

app/flask_app/templates/dcs/hotas.html
{% if joystick %}
<div class="ui card">
    <div class="image">
        <img src="data:image/png;base64,{{ joystick|safe }}" alt="stick" id="stick_data">
    </div>
    <div class="content">
        Stick
        <a id="stick_save">
            <i class="save icon"></i>
        </a>
    </div>
</div>{% endif %}|{% if throttle %}<div class="ui card">
    <div class="image">
        <img src="data:image/png;base64,{{ throttle|safe }}" alt="stick" id="throttle_data">
    </div>
    <div class="content">
        Throttle
        <a id="throttle_save">
            <i class="save icon"></i>
        </a>
    </div>
</div>{% endif %}

app/flask_app/templates/dcs/kneeboard.html
{% extends "base.html" %}
{% block body %}
<script>
    function save_pic() {
        var link = document.createElement("a");
        link.setAttribute("href", $('#data').attr('data'));
        link.setAttribute("download", 'test.miz');
        link.click();
    }
    function upload(data) {
        $.ajax({
            url: "{{ url_for('dcs.kneeboard') }}",
            type: 'POST',
            data: data,
            processData: false,  // tell jQuery not to process the data
            contentType: false,  // tell jQuery not to set contentType
            dataType: 'binary',
            cache: false,
            success: function(res, status, xhr) {
                let filename = xhr.getResponseHeader('Content-Disposition').split('=')[1];
                let blob = new Blob([res], {type: 'application/octetstream'});
                let a = document.createElement('a');
                a.href = window.URL.createObjectURL(blob);
                a.download = filename;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                window.URL.revokeObjectURL(a.href);
            },
            error: function(xhr, text, error) {
              console.log(error)
                $("#error_content").text(xhr.responseText);
                $('.ui.modal').modal('show');
            },
        });
    }

    function dropHandler(ev) {
        // Prevent default behavior (Prevent file from being opened)
        ev.preventDefault();

        if (ev.dataTransfer.items) {
            var file = ev.dataTransfer.files;
            var fd = new FormData();
            fd.append('msn', file[0]);
            // we only support two files. if they drag more, tough.
            if (file.length > 1)
                fd.append('controls2', file[1]);
            upload(fd);
        }
    }

    function dragOverHandler(ev) {
        // Prevent default behavior (Prevent file from being opened)
        ev.preventDefault();
    }
</script>
<div class="ui grid">
    <div class="centered row">
        <div class="ui center aligned basic segment">
            <div class="ui blue inverted segment" ondrop="dropHandler(event);" ondragover="dragOverHandler(event);">
                Drag and drop
                <i class="upload icon"></i>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="five wide column"></div>
        <div class="three wide column">
            <div id="data"></div>
        </div>
        <div class="three wide column">
            <div id="throttle"></div>
        </div>
        <div class="five wide column">
            <a id="stick_save">
                <i class="save icon"></i>
            </a>
        </div>
    </div>
</div>



<div id="error" class="ui modal">
    <div class="header">Error</div>
    <div id="error_content" class="content"></div>
</div>

<script>
    $(document).ready(function () {
      // set up jquery to handle binary data
        /**
         *
         * jquery.binarytransport.js
         *
         * @description. jQuery ajax transport for making binary data type requests.
         * @version 1.0
         * @author Henry Algus <henryalgus@gmail.com>
         *
         */

        // use this transport for "binary" data type
        $.ajaxTransport("+binary", function (options, originalOptions, jqXHR) {
            // check for conditions and support for blob / arraybuffer response type
            if (window.FormData && ((options.dataType && (options.dataType == 'binary')) || (options.data && ((window.ArrayBuffer && options.data instanceof ArrayBuffer) || (window.Blob && options.data instanceof Blob))))) {
                return {
                    // create new XMLHttpRequest
                    send: function (headers, callback) {
                        // setup all variables
                        var xhr = new XMLHttpRequest(),
                            url = options.url,
                            type = options.type,
                            async = options.async || true,
                            // blob or arraybuffer. Default is blob
                            dataType = options.responseType || "blob",
                            data = options.data || null,
                            username = options.username || null,
                            password = options.password || null;

                        xhr.addEventListener('load', function () {
                            var data = {};
                            data[options.dataType] = xhr.response;
                            // make callback and send data
                            callback(xhr.status, xhr.statusText, data, xhr.getAllResponseHeaders());
                        });

                        xhr.open(type, url, async, username, password);

                        // setup custom headers
                        for (var i in headers) {
                            xhr.setRequestHeader(i, headers[i]);
                        }

                        xhr.responseType = dataType;
                        xhr.send(data);
                    },
                    abort: function () {
                        jqXHR.abort();
                    }
                };
            }
        });
        $("#controls").change(function(){
            var formData = new FormData($("#myform")[0]);
            upload(formData);
        });
    });
</script>
{% endblock %}

app/flask_app/templates/dcs/mission.html
{% extends "base.html" %}
{% block body %}
<div class="ui grid">
    <div class="row">
        <div class="one wide column"></div>
        <div class="four wide column">
            <div>
                <div class="ui fluid labeled input">
                    <div class="ui label">
                        Cap at
                    </div>
                    <input type="number" min="0" id="max_count" value="5">
                    <div class="ui label">
                        slots above module count
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="one wide column"></div>
        <div class="five wide column" id="module_search">
            <div class="ui labeled input my_select">
                <div class="ui dropdown label">
                    <div class="text module_count">1</div>
                    <i class="dropdown icon"></i>
                    <div class="menu count_select">
                        <div class="item">1</div>
                        <div class="item">2</div>
                        <div class="item">3</div>
                        <div class="item">4</div>
                        <div class="item">5</div>
                        <div class="item">6</div>
                        <div class="item">7</div>
                        <div class="item">8</div>
                    </div>
                </div>
                <div>
                    <select name="pilots" class="ui search dropdown module_select">
                        <option value="">Planesssssssssssssssssssssssssssss</option>
                        {% for module in modules %}
                            <option value="{{ module[0] }}">{{ module[1] }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="circular ui icon button add_module_select">
                    <i class="icon plus"></i>
                </div>
            </div>
        </div>
        <div class="two wide column">
            <button class="ui positive basic button" id="pilot_search">Search</button>
        </div>
    </div>
    <div class="row">
        <div class="one wide column"></div>
        <div class="fourteen wide column">
            <div id="filter_results"></div>
        </div>
    </div>
</div>
<script>
    function set_pilots(group) {
        $('#pilot_parent_p_grouping_leetsaber').css('display', 'none');
        $('#pilot_parent_' + group).css('display', 'inline');
    };

    function set_filter_response(body) {
        console.log("success :)")
        $('#filter_results').html(body)
    };
    $(function () {
        $('body').on('click', '.add_module_select', function () {
            // add the new filter content
            document.getElementById('module_search').innerHTML += `
            <div class="ui labeled input my_select">
                <div class="ui dropdown label">
                    <div class="text module_count">1</div>
                    <i class="dropdown icon"></i>
                    <div class="menu count_select">
                        <div class="item">1</div>
                        <div class="item">2</div>
                        <div class="item">3</div>
                        <div class="item">4</div>
                        <div class="item">5</div>
                        <div class="item">6</div>
                        <div class="item">7</div>
                        <div class="item">8</div>
                    </div>
                </div>
                <div>
                    <select name="pilots" class="ui search dropdown module_select">
                        <option value="">Planesssssssssssssssssssssssssssss</option>
                        {% for module in modules %}
                            <option value="{{ module[0] }}">{{ module[1] }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="circular ui icon button add_module_select">
                    <i class="icon plus"></i>
                </div>
            </div>
            `;

            // initialize the dropdown for the new filter content
            $('.dropdown').dropdown();

            // update the previous + sign to be a - sign instead
            let button_to_remove = $('.add_module_select')[0];
            button_to_remove.innerHTML = '<i class="icon minus"></i>';
            $(button_to_remove).removeClass('add_module_select').addClass('remove_module_select');
        });

        $('body').on('click', '.remove_module_select', function () {
            $(this).parent().remove()
        });

        $('#pilot_search').click(function() {
            var counts = [];
            var modules = [];
            var cap = $('#max_count').val();

            $(".module_count").map(function() {
                counts.push($(this).text());
            }).get();
            console.log(counts);

            $('.module_select > div .selected').map(function () {
                modules.push($(this).attr('data-value'));
            }).get();
            console.log(modules)

            $.ajax({
                url: "{{ url_for('dcs.list_missions') }}",
                type: "POST",
                data: JSON.stringify({
                    'modules': modules,
                    'counts': counts,
                    'cap': cap,
                }),
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (result) {
                    $('#filter_results').html(result['status'])
                }
            });
        });
    });
</script>
{% endblock %}

app/flask_app/templates/dcs/mission_filter_results.html
<div class="ui grid">
    <div class="one wide column"></div>
        <div class="ui message">
            <div class="header">
                Found <font color=green>{{ match_count }}</font> missions with the requested modules, out of a total of <font color=green>{{ mission_count }}</font>. Filtered to <font color=green>{{ match_count_filtered }}</font> based on max slot count.
            </div>
        </div>
    </div>
</div>
&nbsp;

{% if missions %}
<table class="ui sortable celled table">
    <thead>
        <tr>
            <th>Mission</th>
            <th>Start Time</th>
            <th>Map</th>
            <th>Units</th>
        </tr>
    </thead>
    <tbody>
        {% for details in missions %}
            <tr>
                <td class="two wide">
                    <a href="https://www.digitalcombatsimulator.com/en/files/{{ details['ed_id'] }}">{{ details['name'] }}</a><br>
                    Uploaded {{ details['ed_date'] }}
                </td>
                <td class="one wide">
                    {{ details['time'] }}
                </td>
                <td class="two wide">
                    {{ details['terrain'] }}
                </td>
                <td>
                    <table class="ui very basic collapsing celled table">
                    <tbody>
                    <tr>
                    {% for aircraft, a_details in details['factions']['blue']['aircraft'].items() %}
                            <td>
                                {{ aircraft }}
                            </td>
                    {% endfor %}
                    </tr><tr>
                    {% for aircraft, a_details in details['factions']['blue']['aircraft'].items() %}
                        <td>
                            {{ a_details }}
                        </td>
                    {% endfor %}
                    </tr>
                    </tbody>
                    </table>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div class="ui message">
    <i class="close icon"></i>
    <div class="header">
    Uh oh!
    </div>
    <p>Couldn't find any matches for your query :|</p>
</div>
{% endif %}

app/flask_app/templates/dcs/upload.html
{% extends "base.html" %}

{% block body %}
<link href="http://hayageek.github.io/jQuery-Upload-File/4.0.11/uploadfile.css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://hayageek.github.io/jQuery-Upload-File/4.0.11/jquery.uploadfile.min.js"></script>
<div id="steps">
    <div class="ui ordered steps">
        <div class="active step">
            <div class="content">
                <div class="title">Shipping</div>
                <div class="description">Choose your shipping options</div>
            </div>
        </div>
        <div class="step">
            <div class="content">
                <div class="title">Billing</div>
                <div class="description">Enter billing information</div>
            </div>
        </div>
        <div class="step">
            <div class="content">
                <div class="title">Confirm Order</div>
                <div class="description">Verify order details</div>
            </div>
        </div>
    </div>
</div>
<div id="fileuploader">Upload</div>
<script>
    $(document).ready(function()
    {
        $("#fileuploader").uploadFile({
            url:"{{ url_for('dcs.upload') }}",
            fileName:"controls",
        });
    });
</script>
{% endblock %}

app/flask_app/templates/dcs/x52.html
<div class="ui card">
    <div class="image">
        <img src="data:image/png;base64,{{ joystick|safe }}" alt="stick" id="stick_data">
    </div>
    <div class="content">
        Stick
        <a id="stick_save">
            <i class="save icon"></i>
        </a>
    </div>
</div>|<div class="ui card">
    <div class="image">
        <img src="data:image/png;base64,{{ throttle|safe }}" alt="stick" id="throttle_data">
    </div>
    <div class="content">
        Throttle
        <a id="throttle_save">
            <i class="save icon"></i>
        </a>
    </div>
</div>